services:
  db:
    image: postgres:15
    container_name: backend_learning_platform_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: backend_learning_platform
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .

    container_name: learning_platform

    ports:
      - '5001:5001'

    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://myuser:mypassword@db:5432/backend_learning_platform'

    volumes:
      - .:/src
    command: npm run dev

volumes:
  pgdata:
